const MODULES = {
    USERS: 12,
    CASES: 10,
    LOGS: 15,
    COUNTRIES: 11,
    PERMISSIONS: 13,
    REQUESTS: 14,
    RECYCLE_BIN: 16,
    MY_ACCOUNT: 9,
    DASHBOARD: 8
}

const STATUS_CASE = {
    UNNASIGNED: 12,
    IN_PROGRESS: 13,
    WAITING_VALIDATION: 14,
    WAITING_CONFIRMATION: 15,
    ONHOLD: 16,
    REQUIRES_APPROVAL: 17,
    CLOSED: 18,
    CANCELLED: 19,
}

const STATUS_USER = {
    ACTIVE: 6,
    INACTIVE: 7,
    PENDING_ACTIVATION: 10,
    DELETED: 9
}

const TABLE_MAPPING = {
    [MODULES.USERS]: 'users',
    [MODULES.COUNTRIES]: 'dc',
    [MODULES.CASES]: 'cases'
};

const ROLES_USER = {
    ADMIN: 5,
    TECH: 6,
    DOCTOR: 7,
    SUPPORT: 8
}

module.exports = {
    MODULES,
    STATUS_USER,
    TABLE_MAPPING,
    ROLES_USER,
    STATUS_CASE
}
